NATIONS = [
    'england',
    'france',
    'holland',
    'italy',
    'germany',
    'portugal',
    'spain',
]

DF_ORDER = [
    "overall",
    "fixtures",
    "gk",
    "advanced_gk",
    "shooting",
    "passing",
    "pass_types",
    "goal_and_shot_creation",
    "defensive_actions",
    "possession",
    "playing_time",
    "miscellaneous_tasks",
    "overall_regular_season",
    "home_away_regular_season",
]

STAT_LINKS = {
    "england": {
        "Arsenal": "https://fbref.com/en/squads/18bb7c10/Arsenal-Stats",
        "Manchester_City": "https://fbref.com/en/squads/b8fd03ef/Manchester-City-Stats",
        "Manchester_United": "https://fbref.com/en/squads/19538871/Manchester-United-Stats",
        "Newcastle_United": "https://fbref.com/en/squads/b2b47a98/Newcastle-United-Stats",
        "Tottenham": "https://fbref.com/en/squads/361ca564/Tottenham-Hotspur-Stats",
        "Brighton": "https://fbref.com/en/squads/d07537b9/Brighton-and-Hove-Albion-Stats",
        "Brentford": "https://fbref.com/en/squads/cd051869/Brentford-Stats",
        "Fulham": "https://fbref.com/en/squads/fd962109/Fulham-Stats",
        "Chelsea": "https://fbref.com/en/squads/cff3d9bb/Chelsea-Stats",
        "Liverpool": "https://fbref.com/en/squads/822bd0ba/Liverpool-Stats",
        "Aston_Villa": "https://fbref.com/en/squads/8602292d/Aston-Villa-Stats",
        "Crystal_Palance": "https://fbref.com/en/squads/47c64c55/Crystal-Palace-Stats",
        "Forest": "https://fbref.com/en/squads/e4a775cb/Nottingham-Forest-Stats",
        "Leicester": "https://fbref.com/en/squads/a2d435b3/Leicester-City-Stats",
        "Wolves": "https://fbref.com/en/squads/8cec06e1/Wolverhampton-Wanderers-Stats",
        "West_Ham": "https://fbref.com/en/squads/7c21e445/West-Ham-United-Stats",
        "Leeds": "https://fbref.com/en/squads/5bfb9659/Leeds-United-Stats",
        "Everton": "https://fbref.com/en/squads/d3fd31cc/Everton-Stats",
        "Bournemouth": "https://fbref.com/en/squads/4ba7cbea/Bournemouth-Stats",
        "Southampton": "https://fbref.com/en/squads/33c895d4/Southampton-Stats",
    },
    'france': {
        "Paris Saint-Germain": "https://fbref.com/en/squads/e2d8892c/Paris-Saint-Germain-Stats",
        "Marseille": "https://fbref.com/en/squads/5725cc7b/Marseille-Stats",
        "Lens": "https://fbref.com/en/squads/fd4e0f7d/Lens-Stats",
        "Monaco": "https://fbref.com/en/squads/fd6114db/Monaco-Stats",
        "Rennes": "https://fbref.com/en/squads/b3072e00/Rennes-Stats",
        "Lille": "https://fbref.com/en/squads/cb188c0c/Lille-Stats",
        "Nice": "https://fbref.com/en/squads/132ebc33/Nice-Stats",
        "Reims": "https://fbref.com/en/squads/7fdd64e0/Reims-Stats",
        "Lorient": "https://fbref.com/en/squads/d2c87802/Lorient-Stats",
        "Lyon": "https://fbref.com/en/squads/d53c0b06/Lyon-Stats",
        "Toulouse": "https://fbref.com/en/squads/3f8c4b5f/Toulouse-Stats",
        "Clermont-Foot": "https://fbref.com/en/squads/d9676424/Clermont-Foot-Stats",
        "Montpellier": "https://fbref.com/en/squads/281b0e73/Montpellier-Stats",
        "Nantes": "https://fbref.com/en/squads/d7a486cd/Nantes-Stats",
        "Strasbourg": "https://fbref.com/en/squads/c0d3eab4/Strasbourg-Stats",
        "Brest": "https://fbref.com/en/squads/fb08dbb3/Brest-Stats",
        "Auxerre": "https://fbref.com/en/squads/5ae09109/Auxerre-Stats",
        "Ajaccio": "https://fbref.com/en/squads/7a54bb4f/Ajaccio-Stats",
        "Troyes": "https://fbref.com/en/squads/54195385/Troyes-Stats",
        "Angers": "https://fbref.com/en/squads/69236f98/Angers-Stats",
    }, 
    'spain': {
        "Barcelona": "https://fbref.com/en/squads/206d90db/Barcelona-Stats",
        "Real_Madrid": "https://fbref.com/en/squads/53a2f082/Real-Madrid-Stats",
        "Atletico_Madrid": "https://fbref.com/en/squads/db3b9613/Atletico-Madrid-Stats",
        "Real_Sociedad": "https://fbref.com/en/squads/e31d1cd9/Real-Sociedad-Stats",
        "Betis": "https://fbref.com/en/squads/fc536746/Real-Betis-Stats",
        "Villarreal": "https://fbref.com/en/squads/2a8183b3/Villarreal-Stats",
        "Athletic_Club": "https://fbref.com/en/squads/2b390eca/Athletic-Club-Stats",
        "Rayo_Vallecano": "https://fbref.com/en/squads/98e8af82/Rayo-Vallecano-Stats",
        "Osasuna": "https://fbref.com/en/squads/03c57e2b/Osasuna-Stats",
        "Mallorca": "https://fbref.com/en/squads/2aa12281/Mallorca-Stats",
        "Celta_Vigo": "https://fbref.com/en/squads/f25da7fb/Celta-Vigo-Stats",
        "Girona": "https://fbref.com/en/squads/9024a00a/Girona-Stats",
        "Sevilla": "https://fbref.com/en/squads/ad2be733/Sevilla-Stats",
        "Valladolid": "https://fbref.com/en/squads/17859612/Valladolid-Stats",
        "Espanyol": "https://fbref.com/en/squads/a8661628/Espanyol-Stats",
        "Cadiz": "https://fbref.com/en/squads/ee7c297c/Cadiz-Stats",
        "Valencia": "https://fbref.com/en/squads/dcc91a7b/Valencia-Stats",
        "Getafe": "https://fbref.com/en/squads/7848bd64/Getafe-Stats",
        "Almeria": "https://fbref.com/en/squads/78ecf4bb/Almeria-Stats",
        "Elche": "https://fbref.com/en/squads/6c8b07df/Elche-Stats",
    },
    'germany': {
        "Bayern_Munich": "https://fbref.com/en/squads/054efa67/Bayern-Munich-Stats",
        "Dortmund": "https://fbref.com/en/squads/add600ae/Dortmund-Stats",
        "RB_Leipzig": "https://fbref.com/en/squads/acbb6a5b/RB-Leipzig-Stats",
        "Union_Berlin": "https://fbref.com/en/squads/7a41008f/Union-Berlin-Stats",
        "Freiburg": "https://fbref.com/en/squads/a486e511/Freiburg-Stats",
        "Eintracht_Frankfurt": "https://fbref.com/en/squads/f0ac8ee6/Eintracht-Frankfurt-Stats",
        "Mainz_05": "https://fbref.com/en/squads/a224b06a/Mainz-05-Stats",
        "Wolfsburg": "https://fbref.com/en/squads/4eaa11d7/Wolfsburg-Stats",
        "Bayer_Leverkusen": "https://fbref.com/en/squads/c7a9f859/Bayer-Leverkusen-Stats",
        "Monchengladbach": "https://fbref.com/en/squads/32f3ee20/Monchengladbach-Stats",
        "Werder_Bremen": "https://fbref.com/en/squads/62add3bf/Werder-Bremen-Stats",
        "Koln": "https://fbref.com/en/squads/bc357bf7/Koln-Stats",
        "Augsburg": "https://fbref.com/en/squads/0cdc4311/Augsburg-Stats",
        "Bochum": "https://fbref.com/en/squads/b42c6323/Bochum-Stats",
        "Hertha_BSC": "https://fbref.com/en/squads/2818f8bc/Hertha-BSC-Stats",
        "Stuttgart": "https://fbref.com/en/squads/598bc722/Stuttgart-Stats",
        "Schalke_04": "https://fbref.com/en/squads/c539e393/Schalke-04-Stats",
        "Hoffenheim": "https://fbref.com/en/squads/033ea6b8/Hoffenheim-Stats",
    },
    'italy': {
        "Napoli": "https://fbref.com/en/squads/d48ad4ff/Napoli-Stats",
        "Internazionale": "https://fbref.com/en/squads/d609edc0/Internazionale-Stats",
        "Lazio": "https://fbref.com/en/squads/7213da33/Lazio-Stats",
        "Milan": "https://fbref.com/en/squads/dc56fe14/Milan-Stats",
        "Roma": "https://fbref.com/en/squads/cf74a709/Roma-Stats",
        "Atalanta": "https://fbref.com/en/squads/922493f3/Atalanta-Stats",
        "Juventus": "https://fbref.com/en/squads/e0652b02/Juventus-Stats",
        "Torino": "https://fbref.com/en/squads/105360fe/Torino-Stats",
        "Bologna": "https://fbref.com/en/squads/1d8099f8/Bologna-Stats",
        "Sassuolo": "https://fbref.com/en/squads/e2befd26/Sassuolo-Stats",
        "Udinese": "https://fbref.com/en/squads/04eea015/Udinese-Stats",
        "Fiorentina": "https://fbref.com/en/squads/421387cf/Fiorentina-Stats",
        "Monza": "https://fbref.com/en/squads/21680aa4/Monza-Stats",
        "Empoli": "https://fbref.com/en/squads/a3d88bd8/Empoli-Stats",
        "Lecce": "https://fbref.com/en/squads/ffcbe334/Lecce-Stats",
        "Salernitana": "https://fbref.com/en/squads/c5577084/Salernitana-Stats",
        "Spezia": "https://fbref.com/en/squads/68449f6d/Spezia-Stats",
        "Hellas-Verona": "https://fbref.com/en/squads/0e72edf2/Hellas-Verona-Stats",
        "Cremonese": "https://fbref.com/en/squads/9aad3a77/Cremonese-Stats",
        "Sampdoria": "https://fbref.com/en/squads/8ff9e3b3/Sampdoria-Stats",
    },
    'portugal': {
        "Benfica": "https://fbref.com/en/squads/a77c513e/Benfica-Stats",
        "Porto": "https://fbref.com/en/squads/5e876ee6/Porto-Stats",
        "Braga": "https://fbref.com/en/squads/69d84c29/Braga-Stats",
        "Sporting": "https://fbref.com/en/squads/13dc44fd/Sporting-CP-Stats",
        "Vitoria": "https://fbref.com/en/squads/3f319bc9/Vitoria-Guimaraes-Stats",
        "Arouca": "https://fbref.com/en/squads/0d36ddd4/Arouca-Stats",
        "Casa": "https://fbref.com/en/squads/b20a2b76/Casa-Pia-Stats",
        "Rio": "https://fbref.com/en/squads/eea856da/Rio-Ave-Stats",
        "Famalicao": "https://fbref.com/en/squads/2de656d5/Famalicao-Stats",
        "Boavista": "https://fbref.com/en/squads/37b7e9e2/Boavista-Stats",
        "Chaves": "https://fbref.com/en/squads/bf4e8a13/Chaves-Stats",
        "Vizela": "https://fbref.com/en/squads/b9daacef/Vizela-Stats",
        "Vincente": "https://fbref.com/en/squads/6a329209/Gil-Vicente-FC-Stats",
        "Portimonense": "https://fbref.com/en/squads/a549d6c6/Portimonense-Stats",
        "Estoril": "https://fbref.com/en/squads/00c41b75/Estoril-Stats",
        "Maritimo": "https://fbref.com/en/squads/c1b0f61b/Maritimo-Stats",
        "Pacos": "https://fbref.com/en/squads/f6af6f6f/Pacos-de-Ferreira-Stats",
        "Santa-Clara": "https://fbref.com/en/squads/f5b64cb1/Santa-Clara-Stats",
    },
    'holland': {
        "Feyenoord": "https://fbref.com/en/squads/fb4ca611/Feyenoord-Stats",
        "Ajax": "https://fbref.com/en/squads/19c3f8c4/Ajax-Stats",
        "Alkmaar": "https://fbref.com/en/squads/3986b791/AZ-Alkmaar-Stats",
        "PSV": "https://fbref.com/en/squads/e334d850/PSV-Eindhoven-Stats",
        "Rotterdam": "https://fbref.com/en/squads/146a68ce/Sparta-Rotterdam-Stats",
        "Twente": "https://fbref.com/en/squads/a1f721d3/Twente-Stats",
        "Utrecht": "https://fbref.com/en/squads/2a428619/Utrecht-Stats",
        "Nijmegen": "https://fbref.com/en/squads/fc629994/NEC-Nijmegen-Stats",
        "Waalwijk": "https://fbref.com/en/squads/bb14adb3/RKC-Waalwijk-Stats",
        "Heerenveen": "https://fbref.com/en/squads/193ff7aa/Heerenveen-Stats",
        "Go-Ahead-Eagles": "https://fbref.com/en/squads/e33d6108/Go-Ahead-Eagles-Stats",
        "Fortuna-Sittard": "https://fbref.com/en/squads/bd08295c/Fortuna-Sittard-Stats",
        "Volendam": "https://fbref.com/en/squads/8783f4ee/Volendam-Stats",
        "Vitesse": "https://fbref.com/en/squads/209d7fa2/Vitesse-Stats",
        "Emmen": "https://fbref.com/en/squads/01888db1/Emmen-Stats",
        "Excelsior": "https://fbref.com/en/squads/740cb7d4/Excelsior-Stats",
        "Groningen": "https://fbref.com/en/squads/bec05adb/Groningen-Stats",
        "Cambuur": "https://fbref.com/en/squads/5c9e307a/Cambuur-Stats",
    }, 
}

INFO_LINKS = {
    'england': [
        "https://www.transfermarkt.us/manchester-city/kader/verein/281/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/chelsea-fc/kader/verein/631/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/arsenal-fc/kader/verein/11/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/liverpool-fc/kader/verein/31/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/manchester-united/kader/verein/985/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/tottenham-hotspur/kader/verein/148/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/newcastle-united/kader/verein/762/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/west-ham-united/kader/verein/379/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/leicester-city/kader/verein/1003/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/aston-villa/kader/verein/405/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/wolverhampton-wanderers/kader/verein/543/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/fc-southampton/kader/verein/180/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/brighton-amp-hove-albion/kader/verein/1237/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/fc-everton/kader/verein/29/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/nottingham-forest/kader/verein/703/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/brentford-fc/kader/verein/1148/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/leeds-united/kader/verein/399/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/crystal-palace/kader/verein/873/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/fulham-fc/kader/verein/931/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/afc-bournemouth/kader/verein/989/saison_id/2022/plus/1",
    ],
    'spain': [
        "https://www.transfermarkt.us/real-madrid/kader/verein/418/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/fc-barcelona/kader/verein/131/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/atletico-de-madrid/kader/verein/13/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/real-sociedad/kader/verein/681/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/villarreal-cf/kader/verein/1050/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/real-betis-balompie/kader/verein/150/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/valencia-cf/kader/verein/1049/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/sevilla-fc/kader/verein/368/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/athletic-bilbao/kader/verein/621/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/getafe-cf/kader/verein/3709/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/celta-de-vigo/kader/verein/940/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/ca-osasuna/kader/verein/331/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/girona-fc/kader/verein/12321/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/rcd-espanyol-barcelona/kader/verein/714/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/ud-almeria/kader/verein/3302/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/rayo-vallecano/kader/verein/367/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/rcd-mallorca/kader/verein/237/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/elche-cf/kader/verein/1531/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/real-valladolid-cf/kader/verein/366/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/cadiz-cf/kader/verein/2687/saison_id/2022/plus/1",
    ],
    'germany': [
        "https://www.transfermarkt.com/bayern-munich/kader/verein/27/saison_id/2022/plus/1",
        "https://www.transfermarkt.com/borussia-dortmund/kader/verein/16/saison_id/2022/plus/1",
        "https://www.transfermarkt.com/rb-leipzig/kader/verein/23826/saison_id/2022/plus/1",
        "https://www.transfermarkt.com/bayer-04-leverkusen/kader/verein/15/saison_id/2022/plus/1",
        "https://www.transfermarkt.com/eintracht-frankfurt/kader/verein/24/saison_id/2022/plus/1",
        "https://www.transfermarkt.com/borussia-monchengladbach/kader/verein/18/saison_id/2022/plus/1",
        "https://www.transfermarkt.com/vfl-wolfsburg/kader/verein/82/saison_id/2022/plus/1",
        "https://www.transfermarkt.com/tsg-1899-hoffenheim/kader/verein/533/saison_id/2022/plus/1",
        "https://www.transfermarkt.com/sc-freiburg/kader/verein/60/saison_id/2022/plus/1",
        "https://www.transfermarkt.com/vfb-stuttgart/kader/verein/79/saison_id/2022/plus/1",
        "https://www.transfermarkt.com/1-fc-union-berlin/kader/verein/89/saison_id/2022/plus/1",
        "https://www.transfermarkt.com/1-fsv-mainz-05/kader/verein/39/saison_id/2022/plus/1",
        "https://www.transfermarkt.com/fc-augsburg/kader/verein/167/saison_id/2022/plus/1",
        "https://www.transfermarkt.com/hertha-bsc/kader/verein/44/saison_id/2022/plus/1",
        "https://www.transfermarkt.com/1-fc-koln/kader/verein/3/saison_id/2022/plus/1",
        "https://www.transfermarkt.com/sv-werder-bremen/kader/verein/86/saison_id/2022/plus/1",
        "https://www.transfermarkt.com/fc-schalke-04/kader/verein/33/saison_id/2022/plus/1",
        "https://www.transfermarkt.com/vfl-bochum/kader/verein/80/saison_id/2022/plus/1",
    ],
    'france': [
        "https://www.transfermarkt.us/paris-saint-germain/kader/verein/583/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/stade-rennais-fc/kader/verein/273/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/as-monaco/kader/verein/162/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/olympique-marseille/kader/verein/244/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/ogc-nice/kader/verein/417/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/olympique-lyon/kader/verein/1041/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/losc-lille/kader/verein/1082/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/rc-lens/kader/verein/826/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/fc-nantes/kader/verein/995/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/montpellier-hsc/kader/verein/969/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/rc-strasbourg-alsace/kader/verein/667/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/fc-lorient/kader/verein/1158/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/estac-troyes/kader/verein/1095/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/stade-brestois-29/kader/verein/3911/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/stade-reims/kader/verein/1421/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/fc-toulouse/kader/verein/415/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/angers-sco/kader/verein/1420/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/aj-auxerre/kader/verein/290/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/clermont-foot-63/kader/verein/3524/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/ac-ajaccio/kader/verein/1147/saison_id/2022/plus/1",
    ],
    'italy': [
        "https://www.transfermarkt.us/ac-milan/kader/verein/5/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/inter-milan/kader/verein/46/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/ssc-napoli/kader/verein/6195/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/juventus-fc/kader/verein/506/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/as-roma/kader/verein/12/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/atalanta-bc/kader/verein/800/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/ss-lazio/kader/verein/398/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/acf-fiorentina/kader/verein/430/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/us-sassuolo/kader/verein/6574/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/torino-fc/kader/verein/416/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/udinese-calcio/kader/verein/410/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/bologna-fc-1909/kader/verein/1025/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/ac-monza/kader/verein/2919/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/us-salernitana-1919/kader/verein/380/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/fc-empoli/kader/verein/749/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/spezia-calcio/kader/verein/3522/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/hellas-verona/kader/verein/276/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/us-lecce/kader/verein/1005/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/uc-sampdoria/kader/verein/1038/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/us-cremonese/kader/verein/2239/saison_id/2022/plus/1",
    ],
    'portugal': [
        "https://www.transfermarkt.us/sl-benfica/kader/verein/294/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/fc-porto/kader/verein/720/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/sporting-cp/kader/verein/336/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/sc-braga/kader/verein/1075/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/vitoria-guimaraes-sc/kader/verein/2420/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/fc-famalicao/kader/verein/3329/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/gil-vicente-fc/kader/verein/2424/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/cd-santa-clara/kader/verein/2423/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/gd-estoril-praia/kader/verein/1465/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/portimonense-sc/kader/verein/7378/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/boavista-fc/kader/verein/2503/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/cs-maritimo/kader/verein/1301/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/casa-pia-ac/kader/verein/3268/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/fc-pacos-de-ferreira/kader/verein/2995/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/fc-arouca/kader/verein/8024/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/fc-vizela/kader/verein/6912/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/rio-ave-fc/kader/verein/2425/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/gd-chaves/kader/verein/3325/saison_id/2022/plus/1",
    ],
    'holland': [
        "https://www.transfermarkt.us/ajax-amsterdam/kader/verein/610/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/psv-eindhoven/kader/verein/383/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/feyenoord-rotterdam/kader/verein/234/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/az-alkmaar/kader/verein/1090/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/fc-utrecht/kader/verein/200/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/twente-enschede-fc/kader/verein/317/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/vitesse-arnhem/kader/verein/499/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/sc-heerenveen/kader/verein/306/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/fc-groningen/kader/verein/202/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/fortuna-sittard/kader/verein/385/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/nec-nijmegen/kader/verein/467/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/sparta-rotterdam/kader/verein/468/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/sc-cambuur-leeuwarden/kader/verein/133/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/excelsior-rotterdam/kader/verein/798/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/fc-volendam/kader/verein/724/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/fc-emmen/kader/verein/1283/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/rkc-waalwijk/kader/verein/235/saison_id/2022/plus/1",
        "https://www.transfermarkt.us/go-ahead-eagles/kader/verein/1435/saison_id/2022/plus/1",
    ],
}
